import AppKit

/// Quien avisa cuando alguien copia texto, para los recientes del panel del
/// hover.
///
/// Mira `changeCount` una vez por segundo —un entero, sin leer nada— y sólo
/// cuando cambió lee el texto. Corre únicamente si se pidió en Ajustes.
///
/// **Lo secreto no entra.** Los gestores de contraseñas marcan lo que copian
/// con los tipos de la convención de nspasteboard.org —oculto, transitorio,
/// autogenerado—, y eso se salta sin leer. Tampoco se guarda nada en disco:
/// los recientes viven en memoria (`ElementoReciente`).
@MainActor
final class VigiaDelPortapapeles {
  var alCopiar: ((String) -> Void)?

  private let portapapeles: NSPasteboard
  private var ultimoConteo: Int
  private var tarea: Task<Void, Never>?

  static let cadencia: Duration = .seconds(1)
  /// Más que esto no es algo que alguien vuelva a pegar desde una fila.
  static let largoMaximo = 4_000

  static let tiposSecretos: Set<NSPasteboard.PasteboardType> = [
    NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
  ]

  init(portapapeles: NSPasteboard = .general) {
    self.portapapeles = portapapeles
    ultimoConteo = portapapeles.changeCount
  }

  func encender(_ encendido: Bool) {
    guard encendido != (tarea != nil) else { return }
    tarea?.cancel()
    tarea = nil
    guard encendido else { return }
    // Lo que ya estaba copiado antes de encender no es «reciente».
    ultimoConteo = portapapeles.changeCount
    tarea = Task { [weak self] in
      while !Task.isCancelled {
        try? await Task.sleep(for: Self.cadencia)
        self?.revisar()
      }
    }
  }

  func revisar() {
    let conteo = portapapeles.changeCount
    guard conteo != ultimoConteo else { return }
    ultimoConteo = conteo
    guard let texto = Self.textoLegible(de: portapapeles) else { return }
    alCopiar?(texto)
  }

  /// El texto copiado, o nil si no hay texto o si viene marcado como secreto.
  static func textoLegible(de portapapeles: NSPasteboard) -> String? {
    let tipos = Set(portapapeles.types ?? [])
    guard tipos.isDisjoint(with: tiposSecretos), tipos.contains(.string),
      let texto = portapapeles.string(forType: .string),
      !texto.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    else { return nil }
    return String(texto.prefix(largoMaximo))
  }
}
